name: Build Android
on:
  push:
    branches: [main]
jobs:
        
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
     
      - name: Install dependencies
        run: yarn
        
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk
          
  build-ios:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: 
          yarn
      - run: xcode-select -p
      - name: Install pod dependencies
        run:
          cd ios && pod install
      - name: Build app
        run:     
          xcodebuild -workspace conceitos_rn.xcworkspace -scheme conceitos_rn archive -archivePath conceitos_rn.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./conceitos_rn.xcarchive -exportPath . -exportOptionsPlist conceitos_rn/Info.plist
          mv conceitos_rn.ipa ../conceitos_rn.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: conceitos_rn.ipa
          path: ios/build/
