name: Build Android
on:
  push:
    branches: [main]
jobs:
        
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
     
      - name: Install dependencies
        run: yarn
        
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk
          
  build-ios:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: 
          yarn
      - name: Install pod dependencies
        run:
          cd ios && pod install
      - name: Build app
        run:     
          xcodebuild -workspace myapp.xcworkspace -scheme myapp archive -archivePath myapp.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./myapp.xcarchive -exportPath . -exportOptionsPlist myapp/Info.plist
          mv myapp.ipa ../myapp.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: myapp.ipa
          path: ios/build/
